### ISSUE TITLE
Please make script easy to access values I cant access it

### ISSUE THREAD

**Issue by TariqKhan-1** [mholgatem/Unity-Touch#1]
You did Very Nice job.
This Script is very good but I cant use it in my project because Accessing values is very complicated please make it public to access it easily.
And make Readme file easier to understand for every one.
Only Developer Can understand it and what about other peoples.
Thank you.

**Comment by mholgatem** [comment]
I actually don't provide support for this script. I released it as a general service. You can try checking out the included examples if you are having a hard time figuring it out. You can access most of the values through the `Input.touches` module
